### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by VincentTam** [davan690/davan690.github.io#14]
Hi, this is the maintainer of `staticmanlab` mentioned in your repo's wiki.

It's written on your blog's contact page that the best way to contribute is to fork your repo and to add comments in the form of Git commits.  This requires a GitHub account to start with.  Besides, you need to manually construct a template in case of comments.  This requires a considerate amount of tedious and repetitive Git work from both sides.  I wonder why not consider automating the work by using one of this theme's comment support.

**Comment by davan690** [comment]
Hey Vincent. Sorry I am a total nube and have no idea how to do all that but just wanted to add comments. Thanks for explaining. I changed text on page until I work it out. Thanks for your time

**Comment by davan690** [comment]
p.s what is the best way to use the wiki? Like a glossary of terms/functions for jekyll/git/gh-pages documentation etc? Im not sure the protocol. :/

**Comment by VincentTam** [comment]
I rarely use Wiki on GitHub/GitLab, so I can't tell.  In simple situations, I prefer a README over Wiki since the former can be copied across Git clones.  Though GitHub also treats the later as a Git repo, it seems to be used online.  When the project documentation involves several chapters (your case), then two solutions are possible:

1.  `docs/` folder (can be rendered as GitHub Pages)
2. project wiki on GitHub (your current approach)

Each option has its pros/cons.  I personally prefer the former since I'm a fan of static sites, which deliver contents in a more reliable way than their dynamic counterpart.  You might keep the later for the ease of use and for the convenience of GitHub coders (so that they can keep staying on GitHub).  No one is absolutely better than the other.  Possible factors may include the repo's goal, audience, etc.

**Comment by VincentTam** [comment]
# :speech_balloon: This theme's comment support

:information_source: The following lines in your root-level site config file is responsible for comment support.
https://github.com/davan690/davan690.github.io/blob/0de558d4464947a5b46276e00f92007d559dd95a/_config.yml#L129-L148

# :frowning_woman: Inconvenience of comments stored in databases

:frowning: I'm not familiar with the actual procedures with FB comments.  On [my old GitHub pages + Octopress site](//git.io/vtblog), i used Disqus, but URL refactoring can lead to disappearance of comments.  Changing the URL is complicated.  Having LaTeX inside comments is impossible... Users don't own their comments.

[![Disqus screenshot](https://screenshotscdn.firefoxusercontent.com/images/380d5c94-d3d3-4aca-916e-6a777c8700ce.png)](https://vincenttam.github.io/blog/2017/01/28/moved-to-octopress-3/#disqus_thread)  
Figure: Disqus on [my old GitHub pages + Octopress site](//git.io/vtblog)

# :question: Why go static?

:globe_with_meridians: Static comments on my current [Hugo + Staticman + KaTeX GitLab pages](https://vincenttam.gitlab.io/):  
[![Staticman comment reply](https://screenshotscdn.firefoxusercontent.com/images/1bae706e-d523-41b3-98ab-ce2041d7fab5.png)](https://vincenttam.gitlab.io/post/2018-12-24-staticman-on-framagit/#comment-1)  
Figure: [Staticman](//staticman.net) comments with the theme Beautiful Hugo provided by halogenica/beautifulhugo#222

:bulb: What does "owning my comments" mean?  You can do *whatever* you want with it.  
[![Staticman + KaTeX + Beautiful Hugo](https://screenshotscdn.firefoxusercontent.com/images/c64e8252-7dae-45d5-9cf4-47de4e4a4fc0.png)](https://staticman-gitlab-pages.frama.io/bhdemo/posts/my-second-post/)  
Figure: math in comments

:1234: Static comments are treated like the site's static content, so you can use [KaTeX](https://katex.org/) for math display.

:heavy_check_mark: I ported others [Staticman](//staticman.net) integration code to some Jekyll and Hugo templates.

# :construction_worker_man: Staticman Configurations for Beautiful Jekyll

:email: Please don't hesitate to ping me on GitHub/GitLab/leave a comment on my blog/send me an email to ask for help.

1. :checkered_flag: Invite @staticmanlab as a collaborator to your repository (by going to your repository Settings page, navigate to the Collaborators tab).  
![send invitation to Staticman Lab](https://git.io/fjZPx)  
Image short link: https://git.io/fjZPx
2. :ballot_box_with_check: Help @staticmanlab accept the invitation by going to

        https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>

    In your case, that's

        https://staticman3.herokuapp.com/v3/connect/github/davan690/davan690.github.io

    ![Staticman Lab invitation accepted](https://git.io/fjZXG)  
    Figure: image showing setup for [my fork of this theme](//git.io/bjsm0)  
    Image short link: https://git.io/fjZXG

    ![Staticman Lab shown as collaborator](https://git.io/fjZXZ)  
    Figure: @staticmanlab invited to GitHub repo  
    Image short link: https://git.io/fjZXZ

3. :writing_hand: Fill in your `repository` and `branch` in the Staticman section of `_config.yml`.

    ```yml
     # Staticman support 
     staticman: 
       repository : "davan690/davan690.github.io" # GitHub username/repository eg. "daattali/beautiful-jekyll" 
       branch     : "master" # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml` 
       endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance) 
       reCaptcha: 
         # reCaptcha for Staticman (OPTIONAL) 
         # If you use reCaptcha, you must also set these parameters in staticman.yml 
         siteKey  : # Use your own site key, you need to apply for one on Google 
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret> 
    ```

4. Start commenting.
